version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mynetwork
    depends_on:
      - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mynetwork
    depends_on:
      - server
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=movie_lib
    ports:
      - 5432:5432
    networks:
      - mynetwork
volumes:
  db_data:

networks:
  mynetwork:
    driver: bridge