export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SEARCH_ROUTE = '/'
export const MOVIE_ROUTE = '/movie'
export const FOLDER_ROUTE = '/folder'
export const FOLDERIN_ROUTE = '/folder/in'
export const ACCOUNT_ROUTE = '/account'